In [1]:
%%writefile ../params.py

PARAMS = {'double': 2.0,
          'triple': 3.0,
          'quadruple': 4.0}

Overwriting ../params.py


In [2]:
from pathlib import Path
import torch
torch.manual_seed(42)

data_dir = Path('../data').resolve()
data_dir.mkdir(parents=True, exist_ok=True)
print(data_dir)

t1 = torch.rand(3, 4)
torch.save(t1, data_dir/'t1.pt')

t2 = torch.rand(4, 5)
torch.save(t2, data_dir/'t2.pt')

C:\Users\Prabu\projworks\chtc_toy\data


In [3]:
%%writefile ../main.py

from pathlib import Path
import argparse
import numpy as np
import pandas as pd
import torch
from argparse import ArgumentParser

from params import *

if __name__ == '__main__':
    parser = ArgumentParser()
    parser.add_argument('--data_file',
                        type=str,
                        required=True,
                        action='store')
    parser.add_argument('--param',
                        type=str,
                        default='double',
                        action='store')
    parser.add_argument('--out_dir',
                        type=str,
                        required=True,
                        action='store')
    args = parser.parse_args()
    data_file = Path(args.data_file).resolve()
    factor = PARAMS[args.param]
    out_dir = Path(args.out_dir).resolve()
    
    out_dir.mkdir(parents=True, exist_ok=True)
    out_file = out_dir/f'{data_file.name}_X{int(factor)}.pt'
    
    t = torch.load(data_file)
    tout = t*factor
    torch.save(tout, out_file)

Overwriting ../main.py


In [4]:
t1 = torch.load(Path('../data/t1.pt'))
t1o = torch.load(Path('../out/t1.pt_X2.pt'))
print(t1)
print(t1o)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[1.7645, 1.8300, 0.7657, 1.9186],
        [0.7809, 1.2018, 0.5131, 1.5873],
        [1.8815, 0.2664, 1.8692, 1.1872]])


In [5]:
t2 = torch.load(Path('../data/t2.pt'))
t2o = torch.load(Path('../out/t2.pt_X3.pt'))
print(t2)
print(t2o)

tensor([[0.8694, 0.5677, 0.7411, 0.4294, 0.8854],
        [0.5739, 0.2666, 0.6274, 0.2696, 0.4414],
        [0.2969, 0.8317, 0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062, 0.9516, 0.0753]])
tensor([[2.6082, 1.7031, 2.2233, 1.2882, 2.6563],
        [1.7217, 0.7997, 1.8823, 0.8089, 1.3241],
        [0.8908, 2.4951, 0.3159, 0.8085, 1.0764],
        [0.5981, 1.6416, 0.0185, 2.8547, 0.2258]])
